package routes

import (
	"academy-go-q12021/controllers"
	"github.com/gofiber/fiber"
)

func Setup(app *fiber.App) {

	app.Get("/", controllers.HelloWorld)

	/** This route generates a CSV with the basic pokemon inputted */
	app.Get("/api/pokemon/:name", controllers.GeneratePokemonCSV)

	/** This router expect the CSV generated by the /api/pokemon/:name route */
	app.Post("/api/import", controllers.Import)

	/** Testing endpoints */
	app.Get("/api/read-csv", controllers.ReadCSV)
	app.Post("/api/csv", controllers.WriteCSV)
}
